---
abstract: 'Minimalistic sugar for your Plack'
author:
  - 'Paul Driver <frodwith@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101582, CPAN::Meta::Converter version 2.101600'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flea
requires:
  Carp: 0
  Exception::Class: 0
  Exporter::Declare: 0
  HTTP::Exception: 0
  JSON: 0
  Plack::Request: 0
  Try::Tiny: 0
version: 0.01
